version: "3.9"

networks:
  laravel:
    driver: bridge
    
services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laraveldb}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel
  
  mysql:
    container_name: laravel-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laraveldb}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    ports:
      - "3306:3306"
    networks:
      - laravel
      
  web:
    container_name: laravel-web
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "81:80"
    depends_on:
      - mysql
    links:
      - "mysql:db"
    networks:
      - laravel

  ################
  ##  Optional  ##
  ################

  # redis:
  #   container_name: laravel-redis
  #   image: redis:latest
  #   volumes:
  #     - ./docker/redis:/data
  #   ports:
  #     - "6380:6379"
  #   environment:      
  #     - TZ=Asian/Jakarta
  #   networks:
  #     - laravel
  
  # rabbitmq:
  #   container_name: laravel-rabbitmq
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     - TZ=Asia/Jakarta
  #   volumes:
  #     - ./docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
  #     - ./docker/rabbitmq/log/:/var/log/rabbitmq
  #   networks:
  #     - laravel

